disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 # - cyclomatic_complexity
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - TravelAppTests
identifier_name:
  excluded:
    - id

# file_name:
#  excluded:
#   - CurrencyServiceTestCase.swift